<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PAKU-BLR-01" ignored="0" name="Test" tests="55" failures="6" timestamp="19 Oct 2021 11:54:25 GMT" time="204.521" errors="0">
  <testcase name="@AfterMethod tearDown" time="0.0" classname="TestNgConcepts.AnnotationsGoogleTest">
    <failure type="org.openqa.selenium.WebDriverException" message="java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:6257
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:25:48&amp;apos;
System info: host: &amp;apos;PAKU-BLR-01&amp;apos;, ip: &amp;apos;192.168.29.62&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_152&amp;apos;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:6257
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'PAKU-BLR-01', ip: '192.168.29.62', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_152'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:452)
	at TestNgConcepts.AnnotationsGoogleTest.tearDown(AnnotationsGoogleTest.java:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:6257
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	... 19 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
	... 39 more
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@BeforeMethod setup" time="0.0" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@BeforeMethod setup" time="0.0" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@BeforeMethod setup" time="0.0" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- @BeforeMethod setup -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="test" time="0.02" classname="TestNgConcepts.ExpectedExceptionInTestNG"/>
  <testcase name="test1" time="0.023" classname="TestNgConcepts.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.027" classname="TestNgConcepts.RetryLogicTest1">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at TestNgConcepts.RetryLogicTest1.test1(RetryLogicTest1.java:9)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.009" classname="TestNgConcepts.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="TestNgConcepts.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.005" classname="TestNgConcepts.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="TestNgConcepts.RetryLogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at TestNgConcepts.RetryLogicTest.test1(RetryLogicTest.java:9)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="sum" time="0.008" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="loginTest" time="0.099" classname="TestNgConcepts.TestNgDependsOnMethod"/>
  <testcase name="googleTitleTest" time="0.03" classname="TestNgConcepts.TestNgAnnotations"/>
  <testcase name="googlelogoTest" time="0.002" classname="TestNgConcepts.TestNgAnnotations"/>
  <testcase name="test" time="0.148" classname="TestNgConcepts.InvocationTimeOutTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNgConcepts.InvocationTimeOutTest.test() didn&amp;apos;t finish within the time-out 2">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNgConcepts.InvocationTimeOutTest.test() didn't finish within the time-out 2
]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="sum" time="0.061" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.035" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.002" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.001" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.002" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.006" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.001" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.002" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.001" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.002" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.001" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="setup" time="0.071" classname="TestNgConcepts.SoftAssertTest">
    <failure type="java.lang.AssertionError" message="validation of home page failed expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: validation of home page failed expected [false] but found [true]
	at TestNgConcepts.SoftAssertTest.setup(SoftAssertTest.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- setup -->
  <testcase name="googlesearch" time="0.046" classname="TestNgConcepts.TestNgAnnotations"/>
  <testcase name="sum" time="0.023" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.002" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.002" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.254" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.003" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.004" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.004" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="sum" time="0.003" classname="TestNgConcepts.InvocationCount"/>
  <testcase name="titleTest" time="0.021" classname="TestNgConcepts.AssertionsInTestNG">
    <failure type="java.lang.AssertionError" message="Title is not mached expected [Google123] but found [Google]">
      <![CDATA[java.lang.AssertionError: Title is not mached expected [Google123] but found [Google]
	at TestNgConcepts.AssertionsInTestNG.titleTest(AssertionsInTestNG.java:31)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- titleTest -->
  <testcase name="linkTest" time="0.512" classname="TestNgConcepts.AnnotationsGoogleTest"/>
  <testcase name="titleTest" time="4.045" classname="TestNgConcepts.AnnotationsGoogleTest"/>
  <testcase name="loginTest" time="7.897" classname="TestNgConcepts.DataProviderTestWithoutExcel"/>
  <testcase name="loginTest" time="7.171" classname="TestNgConcepts.DataProviderTestWithExcel"/>
  <testcase name="logoTest" time="15.888" classname="TestNgConcepts.AssertionsInTestNG">
    <failure type="org.openqa.selenium.WebDriverException" message="java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:42035
Build info: version: &amp;apos;3.141.59&amp;apos;, revision: &amp;apos;e82be7d358&amp;apos;, time: &amp;apos;2018-11-14T08:25:48&amp;apos;
System info: host: &amp;apos;PAKU-BLR-01&amp;apos;, ip: &amp;apos;192.168.29.62&amp;apos;, os.name: &amp;apos;Windows 10&amp;apos;, os.arch: &amp;apos;amd64&amp;apos;, os.version: &amp;apos;10.0&amp;apos;, java.version: &amp;apos;1.8.0_152&amp;apos;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[org.openqa.selenium.WebDriverException: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:42035
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'PAKU-BLR-01', ip: '192.168.29.62', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_152'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:92)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
	at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
	at TestNgConcepts.AssertionsInTestNG.logoTest(AssertionsInTestNG.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.net.ConnectException: Failed to connect to localhost/0:0:0:0:0:0:0:1:42035
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:155)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	... 19 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:129)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
	... 39 more
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- logoTest -->
  <testcase name="test3" time="0.004" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.001" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- test4 -->
  <testcase name="test5" time="0.001" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="HomePageTest" time="0.126" classname="TestNgConcepts.TestNgDependsOnMethod"/>
  <testcase name="RegPageTest" time="0.07" classname="TestNgConcepts.TestNgDependsOnMethod"/>
  <testcase name="SearchPageTest" time="0.095" classname="TestNgConcepts.TestNgDependsOnMethod"/>
  <testcase name="test1" time="0.001" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="logoTest" time="9.358" classname="TestNgConcepts.AnnotationsGoogleTest"/>
  <testcase name="test2" time="0.001" classname="TestNgConcepts.AnnotationsGoogleTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="loginTest" time="12.643" classname="TestNgConcepts.DataProviderTestWithoutExcel"/>
  <testcase name="loginTest" time="8.826" classname="TestNgConcepts.DataProviderTestWithExcel"/>
  <testcase name="loginTest" time="5.331" classname="TestNgConcepts.DataProviderTestWithExcel"/>
  <testcase name="loginTest" time="27.934" classname="TestNgConcepts.DataProviderTestWithoutExcel"/>
  <testcase name="loginTest" time="5.885" classname="TestNgConcepts.DataProviderTestWithExcel"/>
  <testcase name="loginTest" time="5.736" classname="TestNgConcepts.DataProviderTestWithExcel"/>
  <testcase name="loginTest" time="9.482" classname="TestNgConcepts.DataProviderTestWithoutExcel"/>
</testsuite> <!-- Test -->
