<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PAKU-BLR-01" ignored="0" name="RetryMultiplefailesTestcases" tests="9" failures="2" timestamp="12 Oct 2021 08:27:41 GMT" time="0.102" errors="0">
  <testcase name="test1" time="0.021" classname="com.DataDriven.test.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="com.DataDriven.test.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="com.DataDriven.test.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="com.DataDriven.test.RetryLogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DataDriven.test.RetryLogicTest.test1(RetryLogicTest.java:9)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.001" classname="com.DataDriven.test.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="com.DataDriven.test.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="com.DataDriven.test.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.001" classname="com.DataDriven.test.RetryLogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.DataDriven.test.RetryLogicTest.test2(RetryLogicTest.java:14)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.004" classname="com.DataDriven.test.RetryLogicTest"/>
</testsuite> <!-- RetryMultiplefailesTestcases -->
