<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="TestNgConcepts.RetryLogicTest" tests="5" time="0.040" ignored="0" failures="1" timestamp="19 Oct 2021 11:54:28 GMT" skipped="4" hostname="PAKU-BLR-01" errors="0">
  <testcase name="test1" time="0.005" classname="TestNgConcepts.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.023" classname="TestNgConcepts.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="TestNgConcepts.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.009" classname="TestNgConcepts.RetryLogicTest">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="TestNgConcepts.RetryLogicTest">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at TestNgConcepts.RetryLogicTest.test1(RetryLogicTest.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- TestNgConcepts.RetryLogicTest -->
